import { memo, useEffect, useMemo, useRef, useState } from 'react'
import type { Project } from './project'
import type { Edit } from './useProject'
import { Preview } from './Preview'
import { Icon } from './icons'
import { snapshot } from './filmEditing'
/** Only mount capture frames while their thumbnail is on screen. */
export const Thumbnail=memo(function Thumbnail({project,id}:{project:Project;id:string}){
  const ref=useRef<HTMLSpanElement>(null),[visible,setVisible]=useState(false),s=project.subjects.find(s=>s.id===id),a=project.assets.find(a=>a.id===id)
  useEffect(()=>{if(!ref.current)return;const observer=new IntersectionObserver(([e])=>setVisible(e.isIntersecting));observer.observe(ref.current);return()=>observer.disconnect()},[])
  return <span ref={ref} className="film-thumb" aria-hidden="true">{visible&&(s?<Preview subject={s}/>:a?.kind==='image'?<img alt="" src={`/__motioneer/projects/${project.id}/assets/${a.id}`}/>:<Icon name="music"/>)}</span>
})
function excerpt(html:string){const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('style,script').forEach(n=>n.remove());return (doc.body.textContent||'').replace(/\s+/g,' ').trim().slice(0,72)}
export function FilmLibrary({project,edit,insert,actions,firstCut,comparison,compare,restore}:{project:Project;edit:Edit;insert:(id:string,at?:number)=>void;actions:React.ReactNode;firstCut:()=>void;comparison:string;compare:(id:string)=>void;restore:(id:string)=>void}){
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('')
  const items=useMemo(()=>[...project.subjects.map(s=>({id:s.id,name:s.name,kind:'component',detail:/^(h[1-6]|div|span|button|article)(\b|[-. ])/i.test(s.name)?excerpt(s.html):'',count:project.motions.filter(m=>m.subjectId===s.id).length})),...project.assets.map(a=>({id:a.id,name:a.name,kind:a.kind,detail:a.kind==='audio'?`${((a.duration||0)/1000).toFixed(1)}s`:'Image',count:0}))],[project.subjects,project.motions,project.assets])
  const shown=items.filter(i=>(filter==='all'||(filter==='components'?i.kind==='component':i.kind!=='component'))&&(i.name+' '+i.detail).toLowerCase().includes(query.toLowerCase())),chosen=items.find(i=>i.id===selected),subject=project.subjects.find(s=>s.id===selected),asset=project.assets.find(a=>a.id===selected)
  return <aside className="library film-library">{actions}<section className="library-filter"><input aria-label="Search library" placeholder="Search library" value={query} onChange={e=>setQuery(e.target.value)}/><div className="tabs">{['all','components','media'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f[0].toUpperCase()+f.slice(1)}</button>)}</div></section>
    <div className="film-assets">{shown.map(item=><div className={'film-asset'+(item.id===selected?' active':'')} key={item.id} draggable onDragStart={e=>{e.dataTransfer.setData('application/x-motioneer-asset',item.id);e.dataTransfer.effectAllowed='copy'}}><button className="asset-preview-button" aria-label={`Preview ${item.name}`} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}><Thumbnail project={project} id={item.id}/><span><b>{item.name}</b>{item.detail&&<small>{item.detail}</small>}{item.kind==='component'&&<small>{item.count?`${item.count} motion${item.count===1?'':'s'}`:'Still capture'}</small>}</span></button><button className="icon-button" aria-label={`Add ${item.name} to film`} title="Add at the playhead" onClick={()=>insert(item.id)}><Icon name="plus"/></button></div>)}{!shown.length&&<p className="hint padded">{query?'No matching assets.':'Capture a component or import media to build your film.'}</p>}</div>
    {chosen&&<section className="library-preview"><div className="section-heading"><span>{chosen.name}</span><button className="icon-button" aria-label="Close asset preview" onClick={()=>setSelected('')}><Icon name="x"/></button></div>{subject?<Preview subject={subject}/>:asset?.kind==='image'?<img alt={asset.name} src={`/__motioneer/projects/${project.id}/assets/${asset.id}`}/>:asset&&<audio controls src={`/__motioneer/projects/${project.id}/assets/${asset.id}`}/>}<button className="full" onClick={()=>insert(chosen.id)}><Icon name="plus"/>Add to film</button></section>}
    <section className="first-cut"><button className="full" disabled={!project.motions.some(m=>m.saved)} title="Choose captures and pace to create an editable first cut" onClick={firstCut}><Icon name="sparkles"/>Create first cut</button></section>
    {(project.tracks.length>0||project.arrangements.length>0)&&<section className="arrangements"><div className="section-heading">Arrangements<button className="icon-button" aria-label="Save arrangement" title="Save this cut, camera and film settings" disabled={!project.tracks.length||project.arrangements.length>=500} onClick={()=>edit(p=>({...p,arrangements:[...p.arrangements,snapshot(p,'Take '+(p.arrangements.length+1))]}))}><Icon name="plus"/></button></div>{project.arrangements.map(a=><div className="arrangement" key={a.id}><button className={comparison===a.id?'active':''} title={comparison===a.id?'Close comparison':'Compare side by side'} onClick={()=>compare(comparison===a.id?'':a.id)}><Icon name="compare"/>{a.name}</button><button className="icon-button" aria-label={'Use '+a.name} title="Restore this arrangement" onClick={()=>restore(a.id)}><Icon name="check"/></button><button className="icon-button" aria-label={'Delete '+a.name} title="Delete arrangement" onClick={()=>edit(p=>({...p,arrangements:p.arrangements.filter(n=>n.id!==a.id)}))}><Icon name="trash"/></button></div>)}</section>}
  </aside>
}
