import { useState } from 'react'
import type { Project, Pace } from './project'
import { firstCut } from './project'
import type { Edit } from './useProject'
import { snapshot } from './filmEditing'
import { Icon } from './icons'
import { Thumbnail } from './FilmLibrary'
import { useDialog } from './interactions'
export function FirstCut({project,edit,close,done}:{project:Project;edit:Edit;close:()=>void;done:()=>void}) {
  const available=project.subjects.filter(s=>project.motions.some(m=>m.subjectId===s.id&&m.saved)),[ids,setIds]=useState(available.map(s=>s.id)),[pace,setPace]=useState<Pace>('calm'),[seconds,setSeconds]=useState(Math.max(6,Math.min(120,project.settings.duration/1000))),[opening,setOpening]=useState(project.tracks.find(t=>t.kind==='title'&&t.name==='Opening')?.text||'Meet your next great idea'),[closing,setClosing]=useState(project.tracks.find(t=>t.kind==='title'&&t.name==='Closing')?.text||'See it in action')
  const ref=useDialog(close),full=project.arrangements.length>=500&&project.tracks.length>0
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section ref={ref} className="modal first-cut-modal" role="dialog" aria-modal="true" aria-label="Create first cut"><div className="modal-heading"><h2>Create first cut</h2><button className="icon-button" aria-label="Close" onClick={close}><Icon name="x"/></button></div><div className="cut-captures">{available.map(s=><label key={s.id}><input type="checkbox" checked={ids.includes(s.id)} onChange={e=>setIds(e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/><Thumbnail project={project} id={s.id}/><span>{s.name}</span></label>)}</div><div className="field-grid"><label className="field"><span>Pace</span><select aria-label="Cut pace" value={pace} onChange={e=>setPace(e.target.value as Pace)}><option value="calm">Calm</option><option value="brisk">Brisk</option><option value="fast">Fast</option></select></label><label className="field"><span>Film length (s)</span><input aria-label="Cut length (s)" type="number" min={6} max={120} value={seconds} onChange={e=>setSeconds(e.target.valueAsNumber)}/></label></div><label className="field"><span>Opening</span><input value={opening} onChange={e=>setOpening(e.target.value)}/></label><label className="field"><span>Closing</span><input value={closing} onChange={e=>setClosing(e.target.value)}/></label>{project.tracks.length>0&&<p className="hint">Your current cut and film settings will be saved as an arrangement so you can return to them.</p>}{full&&<p className="warning">Remove an arrangement to make room for the current cut.</p>}<button className="primary full" disabled={!ids.length||!Number.isFinite(seconds)||seconds<6||seconds>120||full} onClick={()=>{edit(p=>{const input={...p,subjects:p.subjects.filter(s=>ids.includes(s.id))};const cut=firstCut(input,{pace,seconds,opening,closing,background:p.settings.background});return {...cut,subjects:p.subjects,arrangements:p.tracks.length?[...p.arrangements,snapshot(p,'Before first cut '+(p.arrangements.length+1))]:p.arrangements}});done();close()}}><Icon name="sparkles"/>Create cut</button></section></div>
}
