import { useRef } from 'react'
import type { Project, Track, Move } from './project'
import { uid } from './project'
import type { Edit } from './useProject'
import { Icon, type IconName } from './icons'
import { Control } from './controls'
const eases=['linear','ease-in','ease-out','ease-in-out']
export function NumberField({label,value,onChange,min=0,max=120000,step=1,icon}:{label:string;value:number;onChange:(v:number)=>void;min?:number;max?:number;step?:number;icon?:IconName}) {const input=<input aria-label={label} type="number" min={min} max={max} step={step} value={Math.round(value*100)/100} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n))onChange(Math.max(min,Math.min(max,n)))}}/>;return <label className="field"><span>{label}</span>{icon?<Control icon={icon}>{input}</Control>:input}</label>}
function Movement({moves,change,time}:{moves:Move[];change:(moves:Move[])=>void;time:number}) {
  return <><button className="full" onClick={()=>change([...moves,{at:time,duration:1000,x:0,y:0,scale:1.08,ease:'ease-in-out'}])}><Icon name="plus"/>Add movement at playhead</button>{moves.map((m,i)=><div className="movement" key={i}><div className="section-heading">Move {i+1}<button className="icon-button" aria-label={'Remove move '+(i+1)} title="Remove this move" onClick={()=>change(moves.filter((_,n)=>n!==i))}><Icon name="x"/></button></div><div className="field-grid">{(['at','duration','x','y','scale'] as const).map(key=><NumberField key={key} label={key==='at'?'Starts at (s)':key==='duration'?'Duration (s)':key==='scale'?'Scale':key.toUpperCase()+' offset %'} value={key==='at'||key==='duration'?m[key]/1000:m[key]} min={key==='x'||key==='y'?-300:key==='scale'?.05:key==='duration'?.001:0} max={key==='scale'?10:key==='at'||key==='duration'?120:300} step={key==='scale'?.01:.1} onChange={v=>change(moves.map((n,j)=>j===i?{...n,[key]:key==='at'||key==='duration'?v*1000:v}:n))}/>)}</div><label className="field"><span>Easing</span><Control icon="curve" select><select value={m.ease} onChange={e=>change(moves.map((n,j)=>j===i?{...n,ease:e.target.value}:n))}>{eases.map(e=><option key={e}>{e}</option>)}</select></Control></label></div>)}</>
}
/** The frame in miniature: drag the layer to place it, drag its corner to resize it. The numbers below stay for precision, because a thumbnail this wide resolves to about half a percent. */
function Placement({t,project,patch,edit,begin}:{t:Track;project:Project;patch:(v:Partial<Track>)=>void;edit:Edit;begin:()=>void}) {
  const box=useRef<HTMLDivElement>(null)
  function drag(e:React.PointerEvent,resize=false) {
    if(t.locked)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);begin()
    const r=box.current!.getBoundingClientRect(),x=e.clientX,y=e.clientY,at={...t},round=(n:number)=>Math.round(n*10)/10
    const move=(v:PointerEvent)=>{const dx=(v.clientX-x)/r.width*100,dy=(v.clientY-y)/r.height*100
      const changes=resize?(()=>{const w=Math.max(2,Math.min(200,at.width+dx));return {width:round(w),height:round(at.height*w/at.width)}})():{x:round(at.x+dx),y:round(at.y+dy)}
      edit(p=>({...p,tracks:p.tracks.map(n=>n.id===t.id?{...n,...changes}:n)}),false)}
    const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})
  }
  return <div className="placement" ref={box} style={{aspectRatio:`${project.settings.width}/${project.settings.height}`}} title="Drag to place, drag the corner to resize"><div className={'placement-box'+(t.locked?' locked':'')} role="img" aria-label={`${t.name} at ${t.x}% ${t.y}%`} style={{left:t.x+'%',top:t.y+'%',width:t.width+'%',height:t.height+'%'}} onPointerDown={e=>drag(e)}>{!t.locked&&<i className="placement-handle" onPointerDown={e=>drag(e,true)}/>}</div><button className="icon-button" aria-label="Center" title="Center in the frame" onClick={()=>patch({x:(100-t.width)/2,y:(100-t.height)/2})}><Icon name="target"/></button></div>
}
export function Inspector({project,selection,time,edit,begin}:{project:Project;selection:string[];time:number;edit:Edit;begin:()=>void}) {
  const t=project.tracks.find(t=>selection.includes(t.id))
  const patch=(value:Partial<Track>)=>edit(p=>({...p,tracks:p.tracks.map(n=>selection.includes(n.id)&&!n.locked?{...n,...value}:n)}))
  const settings=(value:Partial<Project['settings']>)=>edit(p=>({...p,settings:{...p.settings,...value}}))
  const formats=[['Landscape',1920,1080],['Square',1080,1080],['Portrait',1080,1350],['Vertical',1080,1920]] as const
  return <aside className="inspector">{t?<>
    <section><div className="row"><input className="title-input" aria-label="Layer name" value={t.name} onChange={e=>patch({name:e.target.value})}/><button className="icon-button" aria-label={t.hidden?'Show':'Hide'} title={t.hidden?'Show this layer':'Hide this layer'} onClick={()=>edit(p=>({...p,tracks:p.tracks.map(n=>selection.includes(n.id)?{...n,hidden:!t.hidden}:n)}))}><Icon name={t.hidden?'eye-off':'eye'}/></button><button className="icon-button" aria-label={t.locked?'Unlock':'Lock'} title={t.locked?'Unlock this layer':'Lock this layer'} onClick={()=>edit(p=>({...p,tracks:p.tracks.map(n=>selection.includes(n.id)?{...n,locked:!t.locked}:n)}))}><Icon name={t.locked?'lock':'unlock'}/></button><button className="icon-button" aria-label="Duplicate" title="Duplicate" onClick={()=>edit(p=>({...p,tracks:[...p.tracks,...p.tracks.filter(n=>selection.includes(n.id)).map(n=>({...structuredClone(n),id:uid(),name:n.name+' copy',locked:false}))]}))}><Icon name="copy"/></button></div></section>
    <fieldset disabled={t.locked}>
    {t.kind==='title'&&<section><div className="field"><textarea aria-label="Title" placeholder="Title text" value={t.text||''} onChange={e=>patch({text:e.target.value})}/></div><div className="field-grid"><NumberField label="Font size" value={t.fontSize} min={8} max={500} onChange={v=>patch({fontSize:v})}/><label className="field"><span>Text color</span><input type="color" value={t.color} onChange={e=>patch({color:e.target.value})}/></label></div></section>}
    {t.kind!=='audio'&&<section><h3>Placement</h3><Placement t={t} project={project} patch={patch} edit={edit} begin={begin}/><div className="field-grid">{(['x','y','width','height'] as const).map(key=><NumberField key={key} label={key==='x'?'X position %':key==='y'?'Y position %':key==='width'?'Width %':'Height %'} value={t[key]} min={key==='x'||key==='y'?-300:1} max={300} step={.1} onChange={v=>patch(key==='width'?{width:v,height:t.height*v/t.width}:{[key]:v})}/>)}</div></section>}
    <section><h3>Timing</h3><div className="field-grid"><NumberField label="Appears at (s)" value={t.start/1000} max={120} step={.1} onChange={v=>patch({start:v*1000})}/><NumberField label="Visible for (s)" value={t.duration/1000} min={.1} max={120} step={.1} onChange={v=>patch({duration:v*1000})}/>{t.kind==='component'&&<NumberField label="Motion delay (s)" value={t.entrance/1000} max={120} step={.1} onChange={v=>patch({entrance:v*1000})}/>}</div><label className="field"><span>Linked start</span><Control icon="link" select><select value={t.after?.key||''} onChange={e=>patch({after:e.target.value?{key:e.target.value,mode:'after',gap:0}:undefined})}><option value="">Absolute time</option>{project.tracks.filter(n=>n.id!==t.id&&!n.after).map(n=><option key={n.id} value={n.id}>After {n.name}</option>)}</select></Control></label></section>
    {t.kind==='audio'?<section><h3>Sound</h3><NumberField label="Volume %" value={t.volume*100} max={100} onChange={v=>patch({volume:v/100})}/><NumberField label="Source trim (s)" value={t.sourceStart/1000} max={86400} step={.1} onChange={v=>patch({sourceStart:v*1000})}/><div className="field-grid"><NumberField label="Fade in (s)" value={t.fadeIn/1000} max={120} step={.1} onChange={v=>patch({fadeIn:v*1000})}/><NumberField label="Fade out (s)" value={t.fadeOut/1000} max={120} step={.1} onChange={v=>patch({fadeOut:v*1000})}/></div></section>:<section><h3>Movement</h3><Movement moves={t.moves} time={time} change={moves=>patch({moves})}/></section>}
    </fieldset><section><div className="row"><button className="icon-button" aria-label="Move up" title="Move this layer up" onClick={()=>edit(p=>{const tracks=[...p.tracks],i=tracks.findIndex(n=>n.id===t.id);if(i>0)[tracks[i-1],tracks[i]]=[tracks[i],tracks[i-1]];return {...p,tracks}})}><Icon name="arrow-up"/></button><button className="icon-button" aria-label="Move down" title="Move this layer down" onClick={()=>edit(p=>{const tracks=[...p.tracks],i=tracks.findIndex(n=>n.id===t.id);if(i<tracks.length-1)[tracks[i+1],tracks[i]]=[tracks[i],tracks[i+1]];return {...p,tracks}})}><Icon name="arrow-down"/></button><button className="icon-button danger" aria-label="Remove selected layers" title="Remove the selected layers" disabled={t.locked} onClick={()=>edit(p=>({...p,tracks:p.tracks.filter(n=>!selection.includes(n.id)||n.locked)}))}><Icon name="trash"/></button></div></section>
  </>:<><section><h3>Frame</h3><div className="format-grid">{formats.map(([name,width,height])=><button key={name} className={project.settings.width===width&&project.settings.height===height?'active':''} onClick={()=>settings({width,height})}><i style={{aspectRatio:`${width}/${height}`}}/>{name}<small>{width} × {height}</small></button>)}</div><label className="field"><span>Background</span><input type="color" value={project.settings.background} onChange={e=>settings({background:e.target.value})}/></label><div className="field-grid"><NumberField label="Film length (s)" value={project.settings.duration/1000} min={.1} max={120} onChange={v=>settings({duration:v*1000,to:v*1000,from:Math.min(project.settings.from,v*1000-1)})}/><label className="field"><span>Frame rate</span><Control icon="film" select><select value={project.settings.fps} onChange={e=>settings({fps:Number(e.target.value)})}><option value={30}>30 fps</option><option value={60}>60 fps</option></select></Control></label></div></section><section><h3>Camera</h3><Movement moves={project.camera} time={time} change={camera=>edit(p=>({...p,camera}))}/></section></>}
  </aside>
}
