import { useEffect, useRef, useState } from 'react'
import type { Project, Track, Move } from './project'
import { uid } from './project'
import type { Edit } from './useProject'
import { Icon, type IconName } from './icons'
import { Control } from './controls'
import { resolvedStarts } from './filmMath'
import { clamp, moveClips, trimClip } from './filmEditing'
import { pointerGesture, useDialog } from './interactions'
import type { Gesture } from './interactions'
import { Preview } from './Preview'
export type InspectorContext='selection'|'film'|'camera'
export function NumberField({label,value,onChange,min=0,max=120000,step=1,icon}:{label:string;value:number|undefined;onChange:(v:number)=>void;min?:number;max?:number;step?:number;icon?:IconName}) {
  const [draft,setDraft]=useState<string|null>(null),changed=useRef(false)
  const commit=(raw:string)=>{if(!raw.trim())return;const n=Number(raw);if(Number.isFinite(n)&&clamp(n,min,max)!==value)onChange(clamp(n,min,max))}
  const input=<input aria-label={label} type="number" min={min} max={max} step={step} placeholder={value===undefined?'Mixed':undefined} value={draft??(value===undefined?'':Math.round(value*1000)/1000)} onFocus={e=>{changed.current=false;setDraft(e.target.value)}} onChange={e=>{changed.current=true;setDraft(e.target.value);commit(e.target.value)}} onBlur={e=>{if(changed.current)commit(e.target.value);changed.current=false;setDraft(null)}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>
  return <label className="field"><span>{label}</span>{icon?<Control icon={icon}>{input}</Control>:input}</label>
}
function Movement({moves,change,time,end}:{moves:Move[];change:(moves:Move[])=>void;time:number;end:number}) {
  const [expanded,setExpanded]=useState(-1)
  return <><button className="full" disabled={time>=end} onClick={()=>{setExpanded(moves.length);change([...moves,{at:time,duration:Math.min(1000,end-time),x:0,y:0,scale:1.08,ease:'ease-in-out'}])}}><Icon name="plus"/>Add movement at playhead</button>{moves.map((m,i)=><details className="movement" key={i} open={expanded===i} onToggle={e=>{if(e.currentTarget.open)setExpanded(i)}}><summary onClick={e=>{e.preventDefault();setExpanded(expanded===i?-1:i)}}>Move {i+1}<span>{(m.at/1000).toFixed(1)}s · {(m.duration/1000).toFixed(1)}s</span></summary><div className="field-grid">{(['at','duration','x','y','scale'] as const).map(key=><NumberField key={key} label={key==='at'?'Starts at (s)':key==='duration'?'Duration (s)':key==='scale'?'Scale':key.toUpperCase()+' offset %'} value={key==='at'||key==='duration'?m[key]/1000:m[key]} min={key==='x'||key==='y'?-300:key==='scale'?.05:key==='duration'?.001:0} max={key==='scale'?10:key==='at'?Math.max(0,end-1)/1000:key==='duration'?Math.max(1,end-m.at)/1000:300} step={key==='scale'?.01:.1} onChange={v=>change(moves.map((n,j)=>j===i?{...n,[key]:key==='at'||key==='duration'?v*1000:v}:n))}/>)}</div><label className="field"><span>Easing</span><Control icon="curve" select><select aria-label="Easing" value={m.ease} onChange={e=>change(moves.map((n,j)=>j===i?{...n,ease:e.target.value}:n))}>{['linear','ease-in','ease-out','ease-in-out'].map(e=><option key={e}>{e}</option>)}</select></Control></label><button className="icon-button" aria-label={'Remove move '+(i+1)} title="Remove this move" onClick={()=>change(moves.filter((_,n)=>n!==i))}><Icon name="trash"/></button></details>)}</>
}
function Placement({t,project,edit,gesture}:{t:Track;project:Project;edit:Edit;gesture:Gesture}) {
  const patch=(v:Partial<Track>)=>edit(p=>({...p,tracks:p.tracks.map(n=>n.id===t.id?{...n,...v}:n)}))
  return <div className="placement" style={{aspectRatio:`${project.settings.width}/${project.settings.height}`}} title="Drag to place the layer"><div className={'placement-box'+(t.locked?' locked':'')} role="img" aria-label={`${t.name} at ${t.x}% ${t.y}%`} style={{left:t.x+'%',top:t.y+'%',width:t.width+'%',height:t.height+'%'}} onPointerDown={e=>{if(t.locked)return;const r=e.currentTarget.parentElement!.getBoundingClientRect(),x=e.clientX,y=e.clientY;pointerGesture(e,gesture,v=>patch({x:clamp(t.x+(v.clientX-x)/r.width*100,-300,300),y:clamp(t.y+(v.clientY-y)/r.height*100,-300,300)}))}}/><button className="icon-button" aria-label="Center" title="Center in the frame" onClick={()=>patch({x:(100-t.width)/2,y:(100-t.height)/2})}><Icon name="target"/></button></div>
}
function MotionChooser({project,t,edit,close}:{project:Project;t:Track;edit:Edit;close:()=>void}){
  const ref=useDialog(close),s=project.subjects.find(s=>s.id===t.subjectId)!,motions=project.motions.filter(m=>m.subjectId===t.subjectId),[previewing,setPreviewing]=useState(false),[clock,setClock]=useState(0)
  const span=Math.max(1000,...motions.map(m=>m.duration))+500
  useEffect(()=>{if(!previewing)return;let frame=0;const start=performance.now();const tick=(now:number)=>{setClock((now-start)%span);frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[previewing,span])
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section ref={ref} role="dialog" aria-modal="true" aria-label="Change motion" className="modal motion-chooser"><div className="modal-heading"><h2>Change motion</h2><button className="icon-button" aria-label={previewing?'Pause motion previews':'Play motion previews'} title="Preview all alternatives together" onClick={()=>setPreviewing(!previewing)}><Icon name={previewing?'pause':'play'}/></button><button className="icon-button" aria-label="Close" onClick={close}><Icon name="x"/></button></div><div className="motion-choices">{motions.map(m=><button key={m.id} aria-pressed={t.motionId===m.id} onClick={()=>{edit(p=>({...p,tracks:p.tracks.map(n=>n.id===t.id?{...n,motionId:m.id}:n)}));close()}}><Preview subject={s} motion={m} time={previewing?clock:m.duration*.6}/><span>{m.treatment} · {(m.duration/1000).toFixed(1)}s{m.saved?' · Kept':''}</span></button>)}</div><button className="full" onClick={()=>{edit(p=>({...p,tracks:p.tracks.map(n=>n.id===t.id?{...n,motionId:undefined}:n)}));close()}}>Use still capture</button></section></div>
}
type Props={project:Project;selection:string[];time:number;edit:Edit;gesture:Gesture;pause:()=>void;context:InspectorContext;setContext:(v:InspectorContext)=>void;seek:(v:number)=>void;select:(ids:string[])=>void}
export function Inspector({project,selection,time,edit,gesture,pause,context,setContext,seek,select}:Props) {
  const selected=project.tracks.filter(t=>selection.includes(t.id)),t=selected[0],single=selected.length===1,editable=selected.filter(t=>!t.locked),at=resolvedStarts(project),[chooser,setChooser]=useState(false)
  const patch=(value:Partial<Track>)=>edit(p=>({...p,tracks:p.tracks.map(n=>selection.includes(n.id)&&!n.locked?{...n,...value}:n)}))
  const settings=(value:Partial<Project['settings']>)=>edit(p=>({...p,settings:{...p.settings,...value}}))
  const common=(get:(t:Track)=>number)=>{const values=selected.map(get);return values.every(v=>v===values[0])?values[0]:undefined}
  const start=(t:Track)=>at[project.tracks.indexOf(t)],allVisual=selected.every(t=>t.kind!=='audio'),allAudio=selected.every(t=>t.kind==='audio'),allComponents=selected.every(t=>t.kind==='component')
  return <aside className="inspector film-inspector"><nav className="inspector-tabs tabs" role="tablist" aria-label="Inspector context">{(['selection','film','camera'] as const).map(c=><button key={c} role="tab" aria-selected={context===c} tabIndex={context===c?0:-1} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const tabs=Array.from(e.currentTarget.parentElement!.querySelectorAll<HTMLButtonElement>('[role=tab]:not(:disabled)')),i=tabs.indexOf(e.currentTarget),next=tabs[(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length];next.click();next.focus()}}} disabled={c==='selection'&&!t} className={context===c?'active':''} onClick={()=>setContext(c)}>{c[0].toUpperCase()+c.slice(1)}</button>)}</nav>
    {context==='selection'&&t?<>
      <section><div className="row">{single?<input className="title-input" aria-label="Layer name" value={t.name} onChange={e=>patch({name:e.target.value})}/>:<b className="selection-count">{selected.length} layers selected</b>}<button className="icon-button" aria-label={selected.every(t=>t.hidden)?'Show':'Hide'} title="Toggle selected layers' visibility" onClick={()=>edit(p=>({...p,tracks:p.tracks.map(n=>selection.includes(n.id)&&!n.locked?{...n,hidden:!selected.every(t=>t.hidden)}:n)}))}><Icon name={selected.every(t=>t.hidden)?'eye-off':'eye'}/></button><button className="icon-button" aria-label={selected.every(t=>t.locked)?'Unlock':'Lock'} title="Toggle selected layers' lock" onClick={()=>edit(p=>({...p,tracks:p.tracks.map(n=>selection.includes(n.id)?{...n,locked:!selected.every(t=>t.locked)}:n)}))}><Icon name={selected.every(t=>t.locked)?'lock':'unlock'}/></button><button className="icon-button" aria-label="Duplicate" title="Duplicate selected layers" onClick={()=>{const ids=new Map(selected.map(t=>[t.id,uid()]));edit(p=>({...p,tracks:[...p.tracks,...selected.map(n=>({...structuredClone(n),id:ids.get(n.id)!,name:n.name+' copy',locked:false,after:n.after?{...n.after,key:ids.get(n.after.key)||n.after.key}:undefined}))]}));select([...ids.values()])}}><Icon name="copy"/></button></div><button className="text-button" onClick={()=>seek(start(t))}><Icon name="target"/>Go to clip</button>{editable.length<selected.length&&<p className="hint">{selected.length-editable.length} locked. Unlock to edit.</p>}</section>
      <fieldset disabled={!editable.length}>
        {single&&t.kind==='title'&&<section><label className="field"><span>Title</span><textarea aria-label="Title" value={t.text||''} onChange={e=>patch({text:e.target.value})}/></label><div className="field-grid"><NumberField label="Font size" value={t.fontSize} min={8} max={500} onChange={v=>patch({fontSize:v})}/><label className="field"><span>Text color</span><input type="color" value={t.color} onChange={e=>patch({color:e.target.value})}/></label></div></section>}
        {single&&t.kind==='component'&&<section className="clip-motion"><h3>Motion</h3><div className="row spread"><span>{project.motions.find(m=>m.id===t.motionId)?.treatment||'Still capture'}</span><button onClick={()=>{pause();setChooser(true)}}>Change motion</button></div></section>}
        <section><h3>Timing</h3><div className="field-grid"><NumberField label={single?'Appears at (s)':'Group starts at (s)'} value={Math.min(...selected.map(n=>start(n)))/1000} max={project.settings.duration/1000} step={.1} onChange={v=>edit(p=>moveClips(p,selection,v*1000-Math.min(...selected.map(n=>start(n)))))}/><NumberField label="Visible for (s)" value={common(n=>n.duration/1000)} min={.1} max={project.settings.duration/1000} step={.1} onChange={v=>edit(p=>editable.reduce((next,n)=>trimClip(next,n.id,'right',v*1000-n.duration),p))}/>{allComponents&&<NumberField label="Motion delay (s)" value={common(n=>n.entrance/1000)} max={120} step={.1} onChange={v=>patch({entrance:v*1000})}/>}</div>
          {single&&<details className="advanced"><summary>Linked timing{t.after?' · Linked':''}</summary><label className="field"><span>Linked start</span><Control icon="link" select><select aria-label="Linked start" value={t.after?.key||''} onChange={e=>patch({start:start(t),after:e.target.value?{key:e.target.value,mode:'after',gap:0}:undefined})}><option value="">Absolute time</option>{project.tracks.filter(n=>n.id!==t.id&&!n.after).map(n=><option key={n.id} value={n.id}>{n.name}</option>)}{t.after&&!project.tracks.some(n=>n.id===t.after!.key&&!n.after)&&<option value={t.after.key}>Current linked layer</option>}</select></Control></label>{t.after&&<><label className="field"><span>Relationship</span><select aria-label="Relationship" value={t.after.mode} onChange={e=>patch({after:{...t.after!,mode:e.target.value as 'after'|'with'}})}><option value="after">After</option><option value="with">With</option></select></label><NumberField label="Gap (s)" value={t.after.gap/1000} min={-120} max={120} step={.1} onChange={v=>patch({after:{...t.after!,gap:v*1000}})}/></>}</details>}
        </section>
        {allVisual&&<section><h3>Placement</h3>{single&&<Placement t={t} project={project} edit={edit} gesture={gesture}/>}<div className="field-grid">{(['x','y','width','height'] as const).map(key=><NumberField key={key} label={key==='x'?'X position %':key==='y'?'Y position %':key==='width'?'Width %':'Height %'} value={common(n=>n[key])} min={key==='x'||key==='y'?-300:1} max={300} step={.1} onChange={v=>edit(p=>({...p,tracks:p.tracks.map(n=>selection.includes(n.id)&&!n.locked?{...n,[key]:v,...(key==='width'?{height:clamp(n.height*v/n.width,1,300)}:{})}:n)}))}/>)}</div></section>}
        {allAudio&&<section><h3>Sound</h3><NumberField label="Volume %" value={common(n=>n.volume*100)} max={100} onChange={v=>patch({volume:v/100})}/>{single&&<NumberField label="Source trim (s)" value={t.sourceStart/1000} max={Math.max(0,((project.assets.find(a=>a.id===t.assetId)?.duration||86400000)-t.duration)/1000)} step={.1} onChange={v=>patch({sourceStart:v*1000})}/>}<div className="field-grid"><NumberField label="Fade in (s)" value={common(n=>n.fadeIn/1000)} max={Math.min(...selected.map(n=>n.duration))/1000} step={.1} onChange={v=>patch({fadeIn:v*1000})}/><NumberField label="Fade out (s)" value={common(n=>n.fadeOut/1000)} max={Math.min(...selected.map(n=>n.duration))/1000} step={.1} onChange={v=>patch({fadeOut:v*1000})}/></div></section>}
        {single&&t.kind!=='audio'&&<section><h3>Movement</h3><Movement moves={t.moves} time={Math.max(start(t),time)} end={Math.min(project.settings.duration,start(t)+t.duration)} change={moves=>patch({moves})}/></section>}
      </fieldset><section className="row">{single&&<><button className="icon-button" aria-label="Move up" title="Move layer up" onClick={()=>edit(p=>{const tracks=[...p.tracks],i=tracks.findIndex(n=>n.id===t.id);if(i<=0||t.locked)return p;[tracks[i-1],tracks[i]]=[tracks[i],tracks[i-1]];return {...p,tracks}})}><Icon name="arrow-up"/></button><button className="icon-button" aria-label="Move down" title="Move layer down" onClick={()=>edit(p=>{const tracks=[...p.tracks],i=tracks.findIndex(n=>n.id===t.id);if(i>=tracks.length-1||t.locked)return p;[tracks[i+1],tracks[i]]=[tracks[i],tracks[i+1]];return {...p,tracks}})}><Icon name="arrow-down"/></button></>}<button className="icon-button danger" aria-label="Remove selected layers" title="Remove selected layers" disabled={!editable.length} onClick={()=>{edit(p=>({...p,tracks:p.tracks.filter(n=>!selection.includes(n.id)||n.locked)}));select([])}}><Icon name="trash"/></button></section>
      {chooser&&single&&t.kind==='component'&&<MotionChooser project={project} t={t} edit={edit} close={()=>setChooser(false)}/>}
    </>:context==='camera'?<section><h3>Camera</h3><Movement moves={project.camera} time={time} end={project.settings.duration} change={camera=>edit(p=>({...p,camera}))}/></section>:<section><h3>Frame</h3><div className="format-grid">{([['Landscape',1920,1080],['Square',1080,1080],['Portrait',1080,1350],['Vertical',1080,1920]] as const).map(([name,width,height])=><button key={name} className={project.settings.width===width&&project.settings.height===height?'active':''} onClick={()=>settings({width,height})}><i style={{aspectRatio:`${width}/${height}`}}/>{name}<small>{width} × {height}</small></button>)}</div><label className="field"><span>Background</span><input type="color" value={project.settings.background} onChange={e=>settings({background:e.target.value})}/></label><div className="field-grid"><NumberField label="Film length (s)" value={project.settings.duration/1000} min={.1} max={120} onChange={v=>settings({duration:v*1000,to:v*1000,from:Math.min(project.settings.from,v*1000-1)})}/><label className="field frame-rate"><span>Frame rate</span><Control icon="film" select><select aria-label="Frame rate" value={project.settings.fps} onChange={e=>settings({fps:Number(e.target.value)})}><option value={30}>30 fps</option><option value={60}>60 fps</option></select></Control></label></div>{project.tracks.some((t,i)=>at[i]+t.duration>project.settings.duration)&&<p className="hint">Some clips extend past the film. Increase its length to include them.</p>}</section>}
  </aside>
}
