import { useEffect, useState } from 'react'
import { useDialog } from './interactions'
import { api } from './api'
import { Icon } from './icons'
import { Control } from './controls'
type Config={providers:{id:string;label:string;models:string[]}[];current:{provider:string;model:string;base:string};canCli:boolean}
export function Settings({close}:{close:()=>void}) {
  const ref=useDialog(close)
  const [config,setConfig]=useState<Config|null>(null),[provider,setProvider]=useState('claude-cli'),[model,setModel]=useState(''),[base,setBase]=useState(''),[key,setKey]=useState(''),[note,setNote]=useState('')
  useEffect(()=>{void api<Config>('model').then(c=>{setConfig(c);setProvider(c.current.provider);setModel(c.current.model||'');setBase(c.current.base||'')}).catch(e=>setNote(e.message))},[])
  return <div className="modal-backdrop"><section ref={ref} className="modal" role="dialog" aria-modal="true" aria-label="Model settings"><div className="modal-heading"><h2>Model settings</h2><button className="icon-button" aria-label="Close" title="Close" onClick={close}><Icon name="x"/></button></div><p className="hint">Choose the model that writes your motion. Keys stay on this machine.</p><label className="field"><span>Service</span><Control icon="sparkles" select><select value={provider} onChange={e=>{setProvider(e.target.value);setModel('');setBase('')}}>{config?.providers.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></Control></label><label className="field"><span>Model</span><input list="models" value={model} onChange={e=>setModel(e.target.value)} placeholder="Provider default"/><datalist id="models">{config?.providers.find(p=>p.id===provider)?.models.map(m=><option key={m}>{m}</option>)}</datalist></label>{!['claude-cli','codex-cli'].includes(provider)&&<><label className="field"><span>API key</span><input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Leave blank to keep the saved key"/></label><label className="field"><span>Endpoint</span><input value={base} onChange={e=>setBase(e.target.value)} placeholder="Provider default"/></label></>}<div className="row"><button className="primary" onClick={()=>void api('model',{provider,model,base,...(key?{key}:{})}).then(()=>{setKey('');setNote('Settings saved.')}).catch(e=>setNote(e.message))}>Save settings</button><button onClick={()=>void api('model/check',{}).then(result=>setNote(JSON.stringify(result))).catch(e=>setNote(e.message))}>Test connection</button></div><p role="status">{note}</p></section></div>
}
