/**
 * Build the image pipeline and inline it.
 *
 * The wasm is written into a TypeScript module as base64 rather than emitted as an asset, for
 * one reason: the desktop app loads its page over file://, where fetch is blocked, so an asset
 * beside the bundle is the one shape that does not work everywhere. Inlining costs a third more
 * bytes and works in every shell without a loader path per shell.
 *
 * The generated file is committed, so a fresh clone builds and verifies without Rust installed.
 * Only someone changing the crate needs the toolchain.
 *
 * Run: npm run build:wasm
 */

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.dirname(fileURLToPath(import.meta.url))
const CRATE = path.join(ROOT, 'crates', 'wall-image')
const OUT = path.join(ROOT, 'src', 'imagewasm.ts')
const TARGET = 'wasm32-unknown-unknown'

const cargo = process.env.CARGO ?? path.join(process.env.HOME ?? '', '.cargo', 'bin', 'cargo')

console.log('building the crate ...')
execFileSync(cargo, ['build', '--release', '--target', TARGET], { cwd: CRATE, stdio: 'inherit' })

const wasm = readFileSync(path.join(CRATE, 'target', TARGET, 'release', 'wall_image.wasm'))
const b64 = wasm.toString('base64')

// wrapped, because one 574,000 character line is a file no editor and no diff handles well
const lines = (b64.match(/.{1,120}/g) ?? []).map((l) => `  '${l}',`).join('\n')

writeFileSync(
  OUT,
  `/* Generated by wasm.mjs from crates/wall-image. Do not edit; run npm run build:wasm. */
/* eslint-disable */

/** ${wasm.length.toLocaleString()} bytes of wasm, inlined so it loads over file:// as well as http. */
export const WASM_BASE64 = [
${lines}
].join('')
`,
)

console.log(`wrote ${path.relative(ROOT, OUT)}, ${wasm.length.toLocaleString()} bytes of wasm as ${b64.length.toLocaleString()} of base64`)
