/**
 * Inline the bundled typefaces, the way tools/wasm.mjs inlines the image crate.
 *
 * A shipped page is one file with no requests, so a face travels inside it as base64 or not
 * at all. The subsets are latin, weight axis only: the identity is in the letterforms, and
 * the full axis files cost two to three times as much for play the pages do not use. The
 * output is committed, so a fresh clone builds without running this.
 *
 *   node tools/fonts.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'

const PICK = [
  {
    family: 'Fraunces Variable',
    file: 'node_modules/@fontsource-variable/fraunces/files/fraunces-latin-wght-normal.woff2',
  },
  {
    family: 'Archivo Variable',
    file: 'node_modules/@fontsource-variable/archivo/files/archivo-latin-wght-normal.woff2',
  },
]

const entries = PICK.map(({ family, file }) => {
  const b64 = readFileSync(file).toString('base64')
  console.log(`${family}: ${Math.round(b64.length / 1024)}KB inlined from ${Math.round(readFileSync(file).length / 1024)}KB`)
  return `  { family: '${family}', dataUrl: 'data:font/woff2;base64,${b64}' },`
})

writeFileSync(
  'src/typefaces.ts',
  `/**
 * Generated by tools/fonts.mjs. Do not edit: change the picks there and rerun it.
 *
 * Faces with character that no platform ships, carried inside the page. A face at factory
 * defaults chosen by nobody is the deepest typographic tell of a generated page; these are
 * variable weight 100 to 900, so a world can sit at an extreme the way a person would.
 */
export const TYPEFACES: { family: string; dataUrl: string }[] = [
${entries.join('\n')}
]
`,
)
console.log('wrote src/typefaces.ts')
