/**
 * Inline the bundled typefaces, the way tools/wasm.mjs inlines the image crate.
 *
 * A shipped page is one file with no requests, so a face travels inside it as base64 or not
 * at all. The subsets are latin, weight axis only: the identity is in the letterforms, and
 * the full axis files cost two to three times as much for play the pages do not use. The
 * output is committed, so a fresh clone builds without running this.
 *
 *   node tools/fonts.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'

/**
 * The faces carried inside a page, and why each earns its bytes.
 *
 * Two was not a range. Six face names resolved to about three registers on a typical machine,
 * because sans and grotesk are both neutral grotesques and the two expressive faces fall back
 * to the platform serif and grotesque when they fail to load. These reach registers the
 * platform stacks cannot: an irregular grotesque, a strange display, a didone, a mono with a
 * voice, and a dot matrix. All are SIL Open Font License 1.1, verified in each package.
 *
 * A page still embeds only the faces it wears, so this widens the choice without widening what
 * any one page ships.
 */
const PICK = [
  { family: 'Fraunces Variable', pkg: 'fraunces', why: 'a warm expressive serif' },
  { family: 'Archivo Variable', pkg: 'archivo', why: 'a sturdy display grotesque' },
  { family: 'Bricolage Grotesque Variable', pkg: 'bricolage-grotesque', why: 'a grotesque that is deliberately irregular' },
  { family: 'Syne Variable', pkg: 'syne', why: 'a display face that goes wide and architectural' },
  { family: 'Bodoni Moda Variable', pkg: 'bodoni-moda', why: 'a high contrast didone, the fashion register' },
  { family: 'Martian Mono Variable', pkg: 'martian-mono', why: 'a monospace with an engineered voice' },
  { family: 'Doto Variable', pkg: 'doto', why: 'a dot matrix, and five kilobytes' },
].map((f) => ({ ...f, file: `node_modules/@fontsource-variable/${f.pkg}/files/${f.pkg}-latin-wght-normal.woff2` }))

// the OFL asks that the notice travel with the font, and a page carries the font, so it does
const notice = (pkg) => {
  const text = readFileSync(`node_modules/@fontsource-variable/${pkg}/LICENSE`, 'utf8')
  return (text.match(/^Copyright.*$/m) ?? ['Copyright the project authors'])[0].trim()
}

let raw = 0
const entries = PICK.map(({ family, file, pkg, why }) => {
  const bytes = readFileSync(file)
  raw += bytes.length
  const b64 = bytes.toString('base64')
  console.log(`${family}: ${Math.round(b64.length / 1024)}KB inlined from ${Math.round(bytes.length / 1024)}KB`)
  return `  // ${why}. ${notice(pkg)}, SIL Open Font License 1.1.\n  { family: '${family}', dataUrl: 'data:font/woff2;base64,${b64}' },`
})
console.log(`${PICK.length} faces, ${Math.round(raw / 1024)}KB raw`)

writeFileSync(
  'src/typefaces.ts',
  `/**
 * Generated by tools/fonts.mjs. Do not edit: change the picks there and rerun it.
 *
 * Faces with character that no platform ships, carried inside the page. A face at factory
 * defaults chosen by nobody is the deepest typographic tell of a generated page; these are
 * variable weight 100 to 900, so a world can sit at an extreme the way a person would.
 */
export const TYPEFACES: { family: string; dataUrl: string }[] = [
${entries.join('\n')}
]
`,
)
console.log('wrote src/typefaces.ts')
