/**
 * Bake the shader backdrops, the way tools/fonts.mjs inlines the typefaces.
 *
 * Wall already draws backdrops as WebGL fragment shaders, which is why the preview cells
 * freeze them: nine live shader loops is a heater rather than a wall. Paper Shaders reaches
 * registers ours does not, dithering and halftone and paper grain among them, and those are
 * the ones a page most wants, because they read as print rather than as a gradient.
 *
 * They are rendered once here rather than shipped as a runtime. A page that carries an image
 * stays one file with no framework in it, which is the promise the shipped file makes, and it
 * costs about the same as one typeface. Shipping their engine instead would put an Apache
 * notice inside every page a stranger downloads, for motion that only the focused paper could
 * ever show.
 *
 * Rendered monochrome on purpose: the page tints them with mix-blend-mode from its own
 * palette, so one baked texture serves every look on the wall.
 *
 * Paper Shaders, Apache License 2.0, https://github.com/paper-design/shaders
 * Powered by Paper Shaders: https://shaders.paper.design
 *
 *   node tools/textures.mjs
 */
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'
import { chromium } from 'playwright'

/**
 * Every uniform a shader documents has to be given, or it draws one flat colour and the bake
 * silently produces nothing. The sizing block is the same for all of them; only the last line
 * of each is the texture's own character.
 */
const SIZING = {
  u_originX: 0.5, u_originY: 0.5, u_worldWidth: 0, u_worldHeight: 0,
  u_fit: 0, u_scale: 1, u_rotation: 0, u_offsetX: 0, u_offsetY: 0,
  u_imageAspectRatio: 1,
}
const INK = { u_colorFront: [0, 0, 0, 1], u_colorBack: [1, 1, 1, 1] }

const PICK = [
  {
    id: 'dither',
    from: 'dithering',
    note: 'an ordered Bayer dither, which reads as print rather than as a gradient',
    // hard edged, so png: the same tile as jpeg is three times the bytes and rings at every
    // dot. It is meant to be seen as pixels, so the page scales it without smoothing.
    size: 320,
    format: 'image/png',
    uniforms: { ...SIZING, ...INK, u_shape: 4, u_type: 4, u_pxSize: 3 },
  },
  {
    id: 'dots',
    from: 'dot-grid',
    note: 'an even dot grid, which tiles, so it repeats rather than being blown up to fit',
    // small and tiled: a uniform field has no centre to stretch, which is what went wrong with
    // a halftone rendered once and covered over the page
    size: 240,
    format: 'image/png',
    tile: true,
    uniforms: {
      ...SIZING,
      u_colorBack: [0, 0, 0, 0], u_colorFill: [0, 0, 0, 1], u_colorStroke: [0, 0, 0, 0],
      u_dotSize: 2, u_gapX: 24, u_gapY: 24, u_strokeWidth: 0,
      u_sizeRange: 0, u_opacityRange: 0, u_shape: 1,
    },
  },
]

const EXPORTS = { dithering: 'ditheringFragmentShader', 'dot-grid': 'dotGridFragmentShader' }

// the entry has to sit inside the tree, or esbuild cannot resolve the package from it
const work = mkdtempSync(join('node_modules', '.wall-tex-'))
const entry = join(work, 'entry.mjs')
const bundle = join(work, 'ps.js')
writeFileSync(entry, [
  `export { ShaderMount } from '@paper-design/shaders'`,
  ...PICK.map((p) => `export { ${EXPORTS[p.from]} as ${p.id} } from '@paper-design/shaders'`),
].join('\n'))
execFileSync('npx', ['--yes', 'esbuild', entry, '--bundle', '--minify', '--format=iife', '--global-name=PS', `--outfile=${bundle}`], { stdio: 'pipe' })

const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1200, height: 1200 }, deviceScaleFactor: 1 })
page.on('pageerror', (e) => console.error('  page error:', String(e).slice(0, 160)))
await page.setContent('<div id="m"></div>')
await page.addScriptTag({ content: readFileSync(bundle, 'utf8') })

const entries = []
for (const p of PICK) {
  const url = await page.evaluate(async ({ id, size, uniforms, format }) => {
    const el = document.getElementById('m')
    el.innerHTML = ''
    el.style.width = `${size}px`
    el.style.height = `${size}px`
    // WebGL clears the drawing buffer once it has been composited, so a canvas read after the
    // frame comes back blank unless the context is asked to keep it
    new PS.ShaderMount(el, PS[id], uniforms, { preserveDrawingBuffer: true }, 0)
    await new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r)))
    return el.querySelector('canvas').toDataURL(format, 0.72)
  }, p)
  console.log(`${p.id}: ${Math.round(url.length / 1024)}KB at ${p.size}px`)
  entries.push(`  // ${p.note}\n  ${p.id}: { url: '${url}', tile: ${!!p.tile} },`)
}
await browser.close()

writeFileSync(
  'src/textures.ts',
  `/**
 * Generated by tools/textures.mjs. Do not edit: change the picks there and rerun it.
 *
 * Backdrops baked once rather than run in every page. Each is monochrome, so the page tints it
 * from its own palette and one texture serves every look on the wall.
 *
 * Rendered with Paper Shaders, Apache License 2.0.
 * https://github.com/paper-design/shaders
 */
export const TEXTURES: Record<string, { url: string; tile: boolean }> = {
${entries.join('\n')}
}
`,
)
rmSync(work, { recursive: true, force: true })
console.log('wrote src/textures.ts')
